name: icidasset
version: 1.0.0


dependencies:
  - aeson
  - base >= 4.7 && < 5
  - directory
  - flow
  - icidasset-template
  - lucid
  - shikensu
  - text
  - time
  - unordered-containers
  - warp
  - yaml


executables:
  # ðŸšœ
  build:
    main: Main.hs
    source-dirs:
      - src
      - system/Build
    default-extensions:
      - ExtendedDefaultRules
      - OverloadedStrings

  # ðŸ”
  server:
    main: Main.hs
    source-dirs: system/Server
